@baseUrl = https://localhost:7185
@batchId = 1
@companyId = 1
@payeeId = 5
@paymentId = 1

### Batches

###
GET {{baseUrl}}/api/batches/{{batchId}}

###
GET {{baseUrl}}/api/batches/{{batchId}}

###
GET {{baseUrl}}/api/bat

###
POST {{baseUrl}}/api/batches
Content-Type: application/json
{
    "fileName": "ABD-20260304-04.txt"
}

###
PUT {{baseUrl}}/api/batches/{{batchId}}
Content-Type: application/json
{
    "fileName":"ABD-20260304-04.chg"
}

###
PATCH {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/name",
        "value": "ABD-20260304-04.chg"
    }
]

###
DELETE {{baseUrl}}/api/batches/{{batchesId}}

### Payees

###
POST {{baseUrl}}/api/payees
Content-Type: application/json
{
    "name":"Francine Foxtrot"
}

###
GET {{baseUrl}}/api/payees

###
GET {{baseUrl}}/api/payees/{{payeeId}}

###
PUT {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json
{
    "name":"Erica Echo"
}

###
PATCH {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/name",
        "value": "Emerald Echo"
    }
]

###
DELETE {{baseUrl}}/api/payees/{{payeeId}}

### Payments

###
GET {{baseUrl}}/api/payments
Accept: application/json

###
GET {{baseUrl}}/api/payments/{{paymentId}}

