@baseUrl = https://localhost:7185
@batchId = 1
@companyId = 1
@payeeId = 5
@paymentId = 3

### Batches

###
GET {{baseUrl}}/api/batches

###
GET {{baseUrl}}/api/batches/{{batchId}}

###
POST {{baseUrl}}/api/batches
Content-Type: application/json
{
    "fileName": "ABD-20260304-04.txt",
    "payments": [
        {
            "id": 4,
            "amount": "1750",
            "reference": "ABD-20260404-05",
            "payee": {
                "id": 4,
                "name": "Deanne Delta"
            }
        }
    ]
}

###
PUT {{baseUrl}}/api/batches/{{batchId}}
Content-Type: application/json
{
    "fileName":"ABD-20260304-04.chg"
}

###
PATCH {{baseUrl}}/api/batches/{{batchId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/fileName",
        "value": "ABD-20260304-04.chg"
    }
]

###
DELETE {{baseUrl}}/api/batches/{{batchId}}

### Companies

###
POST {{baseUrl}}/api/companies
Content-Type: application/json
{
    "name":"Countryside"
}

###
GET {{baseUrl}}/api/companies

###
GET {{baseUrl}}/api/companies/{{companyId}}

###
PUT {{baseUrl}}/api/companies/{{companyId}}
Content-Type: application/json
{
    "Name":"Conway"
}

###
PATCH {{baseUrl}}/api/companies/{{companyId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/name",
        "value": "BeachFront"
    }
]

###

DELETE {{baseUrl}}/api/companies/{{companyId}}

###

### Payees

###
POST {{baseUrl}}/api/payees
Content-Type: application/json
{
    "name":"Francine Foxtrot"
}

###
GET {{baseUrl}}/api/payees

###
GET {{baseUrl}}/api/payees/{{payeeId}}

###
PUT {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json
{
    "name":"Erica Echo"
}

###
PATCH {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/name",
        "value": "Emerald Echo"
    }
]

###
DELETE {{baseUrl}}/api/payees/{{payeeId}}

### Payments

###
GET {{baseUrl}}/api/payments
Accept: application/json

###
GET {{baseUrl}}/api/payments/{{paymentId}}

###
POST {{baseUrl}}/api/payments
Content-Type: application/json
{
    "amount": "2000",
    "reference": "ABD-20260404-03",
    "payee": {
        "id": 3,
        "name": "Hayley Hotel"
    },
    "paymentType": 1
}

###
PUT {{baseUrl}}/api/payments/{{paymentId}}
Content-Type: application/json
{
    "amount": "2200",
    "reference": "ABD-20260404-03",
    "payee": {
        "id": 3,
        "name": "Hayley Hotel"
    },
    "paymentType": 1
}

###
PATCH {{baseUrl}}/api/payments/{{paymentId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/amount",
        "value": "3000"
    }
]

###
DELETE {{baseUrl}}/api/payments/{{paymentId}}