@baseUrl = https://localhost:7185
@batchId = 1
@companyId = 1
@payeeId = 10
@paymentId = 1

###
GET {{baseUrl}}/api/companies/{{companyId}}/batches

###
GET {{baseUrl}}/api/companies/{{companyId}}/batches/{{batchId}}

###
GET {{baseUrl}}/api/companies

###
GET {{baseUrl}}/api/companies/{{companyId}}

###
POST {{baseUrl}}/api/payees
Content-Type: application/json
{
    "name":"Francine Foxtrot"
}

###
GET {{baseUrl}}/api/payees

###
GET {{baseUrl}}/api/payees/{{payeeId}}

###
PUT {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json
{
    "name":"Erica Echo"
}

###
PATCH {{baseUrl}}/api/payees/{{payeeId}}
Content-Type: application/json-patch+json
[
    {
        "op": "replace",
        "path": "/name",
        "value": "Emerald Echo"
    }
]

###
DELETE {{baseUrl}}/api/payees/{{payeeId}}

###
GET {{baseUrl}}/api/payments
Accept: application/json

###
GET {{baseUrl}}/api/payments/{{paymentId}}

